### ISSUE TITLE
Add support for project_prefixes

### ISSUE THREAD

**Issue by sjn** [guillaumeaubert/App-GitHooks-Plugin-ForceBranchNamePattern#2]
Hei,

Would it be possible to make this module look for the items in $project_prefixes, just like in some of the other plugins?

Thanks,
- Salve

**Comment by guillaumeaubert** [comment]
Hi Salve,

Good idea, thank you for pointing it out! I just added the support for $project_prefixes: https://metacpan.org/pod/release/AUBERTG/App-GitHooks-Plugin-ForceBranchNamePattern-v1.1.3/lib/App/GitHooks/Plugin/ForceBranchNamePattern.pm#project_prefixes

Guillaume
